#!/bin/bash

#Copyright © 2014 Damian Majchrzak (DamiaX)
#http://damiax.github.io/kernelup/

rm -rf $HOME/.KernelUP_data/*.log;
kernelup -k;

for (( i=1; $i <= 2; )) ; do
sleep 3600;
kernelup -k;
done;
