#!/bin/bash

#Copyright © 2015 Damian Majchrzak (DamiaX)
#http://damiax.github.io/kernelup/

temp=".temp";
ps -e | grep 'kernelup-init' >$temp

if [ -s $temp ]
 then
killall 'sleep';
killall kernelup-init
rm -rf $temp;
else
rm -rf $temp;
fi
kernelup-init;
